services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fin_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Bangkok
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
      - ./initdb/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro  
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fin_agent -h 127.0.0.1 -p 5432 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20


  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  
      - "6335:6334" 
    volumes:
      - qdrant_data:/qdrant/storage

  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7476:7474"  # Browser (HTTP)
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf
      - neo4j_plugins:/plugins

  # CLI tiện lợi để vào psql qua Compose (không cần cài psql trên Windows)
  postgres-client:
    image: postgres:16
    container_name: postgres-client
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: password
    # Mở psql kết nối tới service 'postgres' trong mạng nội bộ Compose
    entrypoint: ["bash", "-lc", "psql -h postgres -U postgres -d fin_agent"]
    tty: true
    stdin_open: true

volumes:
  pg_data:
  qdrant_data:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_plugins:
