[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "fastapi[standard]>=0.116.1",
    "uvicorn[standard]",
    "sqlalchemy",
    "psycopg2-binary",
    "python-dotenv",
    "firebase-admin",
    "authlib",
    "pydantic",
    "python-multipart"
]

[tool.uv]
# Lưu môi trường ảo ngay trong thư mục dự án
venv = ".venv"
