[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
   "authlib>=1.6.5",
   "docling>=2.55.1",
   "fastapi[standard]>=0.118.0",
   "fastembed>=0.4.2",
   "firebase-admin>=7.1.0",
   "flagembedding>=1.3.5",
   "langchain>=0.3.27",
   "langchain-community>=0.3.31",
   "langchain-core>=0.3.78",
   "langchain-google-genai>=2.1.12",
   "langchain-neo4j>=0.5.0",
   "llama-index>=0.14.4",
   "llama-index-embeddings-huggingface>=0.6.1",
   "llama-index-llms-google-genai>=0.6.2",
   "neo4j>=5.28.2",
   "onnxruntime>1.17.3",
   "passlib[bcrypt]>=1.7.4",
   "pdf2docx>=0.5.8",
   "pdf2image>=1.17.0",
   "psycopg2>=2.9.10",
   "psycopg2-binary>=2.9.10",
   "pydantic>=2.12.0",
   "pydantic-settings>=2.11.0",
   "pymupdf>=1.26.4",
   "pytesseract>=0.3.13",
   "python-dotenv>=1.1.1",
   "python-jose[cryptography]>=3.5.0",
   "python-multipart>=0.0.20",
   "qdrant-client>=1.15.1",
   "sqlalchemy>=2.0.43",
   "unidecode>=1.4.0",
   "uvicorn[standard]>=0.37.0",
]
