[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "authlib>=1.6.1",
    "docling==2.43.0",
    "fastapi[standard]>=0.116.1",
    "firebase-admin>=7.1.0",
    "pdf2docx==0.5.8",
    "pdf2image==1.17.0",
    "psycopg2-binary>=2.9.10",
    "pydantic==2.11.7",
    "pymupdf==1.26.3",
    "pytesseract==0.3.13",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.42",
    "uvicorn[standard]>=0.35.0",
    "langchain>=0.0.1",
    "langchain-neo4j>=0.1.0",
    "langchain-community>=0.0.1",
    "neo4j>=5.21",
    "llama-index>=0.13.3",
    "llama-index-embeddings-huggingface>=0.6.0",
    "llama-index-llms-google-genai>=0.3.0",
    "qdrant-client>=1.15.1",
    "fastembed>=0.7.1",
]
